# Generated by Django 5.2.15 on 2026-06-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('professional', 'Professional / Corporate'), ('creative', 'Creative / Modern'), ('minimalist', 'Minimalist / Clean'), ('academic', 'Academic / Research'), ('entry_level', 'Entry Level / Student')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('template_dir', models.CharField(help_text='Directory name within resume_templates/', max_length=200)),
                ('accent_color', models.CharField(default='#000000', help_text='Primary accent color hex code', max_length=7)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='template_previews/')),
                ('is_ats_friendly', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supports_multi_page', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume Template',
                'verbose_name_plural': 'Resume Templates',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
